### ISSUE TITLE
Problem when using blend_psf.fit function

### ISSUE THREAD

**Issue by demax58484** [fred3m/scarlet#55]
There is an error when I am using blend_psf.fit funtion. Concisely, the error is like this:

/export/home/lsst_stack/python/miniconda3-4.2.12/lib/python3.5/site-packages/scarlet-0.2.fd9e460-py3.5-linux-x86_64.egg/scarlet/blend.py in get_model(self, m, combine, combine_source_components, use_sed, flat)
    240                 model_img = np.zeros((source.K,) + (self._img.shape))
    241                 for k in range(source.K):
--> 242                     model_img[k][source.bb] = model[k][model_slice]
    243             return model_img
    244 

ValueError: could not broadcast input array from shape (3,15,14) into shape (3,15,0)

The input is 400 by 400 image, but it seems that if I use 200 by 200 image, I can successfully run the program. The whole error report is in the attachment.

[Error.txt](https://github.com/fred3m/scarlet/files/2142066/Error.txt)

**Comment by pmelchior** [comment]
Hi Mengxin. The logfile is indeed useful. First, you run with an awful lot of sources (>510), that makes things slow but isn't a problem in itself. The series of statements `No flux in peak ...` indicates that you either flip the x/y coordinates in the source initialization (we're using the C convention of `(y,x)` for coordinates) or that you have a large number of very faint detection.

What happens in either case is that the modeling cannot lock onto a peak, which means that the centers of those object cannot be determined and can eventually move off the image. The error is then thrown because at least one of those sources has no pixel from within the image (it has shape `(3,15,0)`, which is necessarily empty).

Can you check the coordinate convention and the SNR of the catalog ids 8, 40, 41, ...?

**Comment by demax58484** [comment]
I used sep to generate catalog. I switched the y and x here and it comes out much more error(No flux in peak xxx). So I think order of y and x is correct.

I do not know how to check the SNR. Is it good to use the catalog[8]['tnpix']/catalog[8]['npix']?
