### ISSUE TITLE
Component shift is off

### ISSUE THREAD

**Issue by lorena21395** [fred3m/scarlet#56]
Here is the output from the logger showing that one component is shifted by a very large amount:

```DEBUG:scarlet.blend:shifting component (1, 0) by (-0.010/0.207) to (31.719/25.764) in it 180
DEBUG:scarlet.blend:shifting component (0, 0) by (-0.048/0.218) to (32.887/32.236) in it 190
DEBUG:scarlet.blend:shifting component (1, 0) by (-89806566564.740/-75030309405.693) to (-89806566533.021/-75030309379.929) in it 190
DEBUG:scarlet.blend:no flux in component (1, 0), skipping recentering in it 200
DEBUG:scarlet.blend:shifting component (0, 0) by (-0.024/0.018) to (32.863/32.255) in it 200```

**Comment by pmelchior** [comment]
just for reference, this is an example file with a 3-band image that show the failure after ~130 iteration in my tests
[multi_band_im.fits.gz](https://github.com/fred3m/scarlet/files/2186659/multi_band_im.fits.gz)

**Comment by pmelchior** [comment]
Here's what happens: when we use acceleration for the `bpgm` method, there's an oscillation of the colors and associated morphologies that doesn't decay. Even worse, it builds up until the solutions jump off the rails:
![test_it_130](https://user-images.githubusercontent.com/1463403/42648034-a4943b3e-85d3-11e8-9257-3de549ba4ef1.gif)
The problem does not arise within 600 iterations if the acceleration is switched off.

The non-convergence here is a puzzle since there are convergence proofs that should apply here.

**Comment by esheldon** [comment]
Looks like one of those animations of a binary neutron star merger :)

**Comment by pmelchior** [comment]
Let's call *Nature* ...

**Comment by pmelchior** [comment]
Keeping this productive: There are two tasks here:
* prevent a source from moving off the frame
* finding out why this optimization blows up

For the first one, we have to be somewhat careful because we need to allow a source center to be outside of the observed frame as long as it has flux that is on the inside.

**Comment by fred3m** [comment]
For the second point I think we should look into the algorithm in [Bubeck 2015](https://arxiv.org/pdf/1405.4980.pdf) for accelerated geometric descent (see a brief summary in [this](https://blogs.princeton.edu/imabandit/2015/06/30/revisiting-nesterovs-acceleration/) blog post). It's similar to Nesterov acceleration except that it appears to be more stable and intuitive to understand why it works, and thus when it breaks down. They claim that it also has a performance increase, although I haven't verified this.

**Comment by pmelchior** [comment]
This problem will not arise anymore since as of v0.5 we don't optimize for a source center. The source is modeled over the entire image, instead of in the center of its own box. Some proximal updates may require to know a center but only in model space as opposed to image space where noise and blending can lead to instabilities.
