### ISSUE TITLE
A mistake in "blend.py"

### ISSUE THREAD

**Issue by demax58484** [fred3m/scarlet#59]
I think there is something wrong with the codes in 'blend.py' in latest version. That is on the 137th row. There is:
```
c._gamma(pos, self._img.shape, offset_int=source.center_int) for c in self.components 
```
While in the gamma definition, there is:
```
def __init__(self, psfs=None, center=None, dy=0, dx=0): 
```
The "pos" is correspongding to the "center", but the input shape of dy and dx does not match

**Comment by pmelchior** [comment]
There's indeed something wrong there, but not what you think. The first line doesn't call the constructor of `Gamma`, it calls its `__call__` method. However, due to a change we made, this has a different signature now, so that line 137 is indeed incorrect and will raise an error.

The problem ties in with more sweeping changes we plan to make soon. I will therefore not fix it now, but replace the incorrect line with a proper error message.
