### ISSUE TITLE
Observation should specify PSFs by default

### ISSUE THREAD

**Issue by pmelchior** [fred3m/scarlet#89]
This came up [during a PR](https://github.com/fred3m/scarlet/pull/87#discussion_r291726061).

In essence, observations should only have `psfs=None` if there's actually no PSF. We've used this setting as default in cases when no PSF matching is used, but we may want to tweak the PSF of our internal model, e.g. by oversampling `Blend` with a narrower PSF, which would require the user to remember that they now have to specify the observation PSF.

My proposal is minimal. Instead of https://github.com/fred3m/scarlet/blob/master/scarlet/observation.py#L129 (or the same location in `LowResObservation`), use `if self.psfs is not None or self.psfs != scene.psfs` 

This will work as intended in all cases apart from this one: observation has a PSF, but scene doesn't, which should never occur.

**Comment by fred3m** [comment]
I'll restate my objection that we should only do this if we implement a `PSF` class. Checking element by element if two arrays are the same is non-trivial and with 43x43 pixel PSFs for LSST this is non-negligible. The lack of that object is the reason we didn't check for that before.

**Comment by pmelchior** [comment]
If done properly, this will be a reference comparison. So, we should write `if psf1 is not psf2`

**Comment by fred3m** [comment]
Agreed, `if self.psfs is not None and self.psfs is not scene.psfs` should work, provided we modify the initialization slightly. During initialization we set `self.psfs=np.array(psfs)` and similar for images in order to make sure that we are dealing with numpy arrays instead of lists or some other iterable type. In that case `self.psfs is not scene.psfs == True` even if we passed the same array to both initializations. So we would be giving up some robustness in the code by *requiring* the user to pass `psfs` as an array in order to have this functionality.
